apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ingress
spec:
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: redis-haproxy-tcp
      protocol: TCP
      port: 6380
      targetPort: 6380
    - name: sentinel
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: redis-tcp-port
      protocol: TCP
      port: 6379
      targetPort: 6379

