spec:
  template:
    spec:
      containers:
      - name: nginx-ingress-microk8s
        ports:
         - name: redis-haproxy-tcp
           containerPort: 5120
           hostPort: 5120
         - name: sentinel
           containerPort: 5000
           hostPort: 5000
         - name: redis-tcp-port
           containerPort: 6379
           hostPort: 6379


